// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDVx-97Bh9s5Nb7FC9-U8b7zNe1oWZiJvY',
//     appId: '1:893501730493:web:7177a746c2dc9a4e5651d4',
//     messagingSenderId: '893501730493',
//     projectId: 'sushil-portfolio',
//     authDomain: 'sushil-portfolio.firebaseapp.com',
//     storageBucket: 'sushil-portfolio.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCiV5-waE7ZifK5IPuDYBA1ntNK8XDRd4g',
//     appId: '1:893501730493:android:cd1c7fd51451e1f75651d4',
//     messagingSenderId: '893501730493',
//     projectId: 'sushil-portfolio',
//     storageBucket: 'sushil-portfolio.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA6lcUZ9L56Qr2sO5GoRGYZBMItKQEyRBA',
//     appId: '1:893501730493:ios:eac447d4347559125651d4',
//     messagingSenderId: '893501730493',
//     projectId: 'sushil-portfolio',
//     storageBucket: 'sushil-portfolio.appspot.com',
//     iosBundleId: 'com.example.responsivePortfolio',
//   );
// }
